Repository qin-team-recipe/06-recipe-app, pull requests merged in 2023-07, with the labels that each got.

#71 feat: :lipstick: add twotab components.
  package-lock.json
  package.json
  src/app/(app)/_components/TabBar/TabItem.tsx
  src/app/(app)/_components/TabBar/Tabar.stories.ts
  src/app/(app)/_components/TabBar/index.tsx
Labels: enhancement, Frontend, UI

#67 Feature/#61 my recipe visibility badge
  src/app/(app)/recipe/[recipeId]/MyRecipeVisibilityBadge/MyRecipeVisibilityBadge.stories.ts
  src/app/(app)/recipe/[recipeId]/MyRecipeVisibilityBadge/MyRecipeVisibilityBadge.tsx
  src/app/(app)/recipe/[recipeId]/MyRecipeVisibilityBadge/index.tsx
Labels: Frontend

#76 feat: :sparkles: add recipeList Components and Story.
  src/app/(app)/_components/RecipeList/index.stories.tsx
  src/app/(app)/_components/RecipeList/index.tsx
  src/app/(app)/_components/RecipeListItem/index.stories.tsx
  src/app/(app)/_components/RecipeListItem/index.tsx
  src/app/(app)/_pages/Fav.tsx
  src/app/(app)/fav/page.tsx
  src/types/index.ts
  src/types/recipe.ts
Labels: UI

#75 feat: :sparkles: Create ActionButton
  src/components/ActionButton/ActionButton.stories.ts
  src/components/ActionButton/ActionButton.tsx
  src/components/ActionButton/index.tsx
Labels: UI

#78 feat: :sparkles: add sectionHeader Components.
  src/app/(app)/_components/SectionHeader/inde.stories.tsx
  src/app/(app)/_components/SectionHeader/index.tsx
  src/app/(app)/_pages/Fav.tsx
Labels: UI

#79 feat: :sparkles: add heroImage Components.
  src/app/(app)/_components/HeroImage/HeroBackButton.tsx
  src/app/(app)/_components/HeroImage/index.stories.tsx
  src/app/(app)/_components/HeroImage/index.tsx
  src/components/Icons/index.ts
  src/components/Icons/index.tsx
Labels: UI

#80 Feature/#38-add-search-section
  package-lock.json
  package.json
  src/app/(app)/_components/ChefList/index.tsx
  src/app/(app)/_components/SearchSection/Input.tsx
  src/app/(app)/_components/SearchSection/SearchInput.tsx
  src/app/(app)/_components/SearchSection/index.stories.tsx
  src/app/(app)/_components/SearchSection/index.tsx
  src/app/(app)/_hooks/useSearchDebounce.ts
  src/app/(app)/_pages/RootPage.tsx
  src/app/(app)/page.tsx
  src/components/BackButton/BackButton.stories.ts
  src/components/BackButton/BackButton.tsx
  src/components/BackButton/index.tsx
  src/lib/utils.ts
Labels: UI

#81 feat: :sparkles: add navigation components.
  package-lock.json
  package.json
  src/app/(app)/_components/ChefListItem/index.tsx
  src/app/(app)/_components/Navigation/BottomNavItem.tsx
  src/app/(app)/_components/Navigation/Navigation.tsx
  src/app/(app)/layout.tsx
  src/components/Icons/index.tsx
Labels: UI

#83 feat: :sparkles: add SocialMediaNav Components.
  src/app/(app)/_components/SocialMediaNav/SocialMediaNav.stories.ts
  src/app/(app)/_components/SocialMediaNav/SocialMediaNav.tsx
  src/app/(app)/_components/SocialMediaNav/index.tsx
  src/components/Icons/index.tsx
Labels: UI

#86 feat: :sparkles: add RecipeStep Components.
  src/app/(app)/_components/RecipeStep/index.stories.tsx
  src/app/(app)/_components/RecipeStep/index.tsx
  src/app/(app)/_components/RecipeStepItem/index.stories.tsx
  src/app/(app)/_components/RecipeStepItem/index.tsx
Labels: UI
